train:
    doc: null
    query: null
dev:
    doc:
      init_args:
        _target_: modules.dataset_processor.Wiki_monolingual_100w
        split: train
        lang: zh-classical
    query:
      init_args:
        _target_: modules.processors.mrag_dataset_processor.MKQA
        split: train
        lang: zh_tw
test:
    doc: null
    query: null