system: "You are a helpful assistant. Your task is to extract relevant information from provided documents and to answer to questions as short as possible. Sort the provided documents by relevance before generating the answer"
user: "Background:\n{docs}\n\nQuestion: {question}"
system_without_docs: "You are a helpful assistant. Answer the questions as short as possible."
user_without_docs: "Question: {question}"