dev:
  doc:
    init_args:
      _target_: modules.dataset_processor.Wiki_monolingual_100w
      lang: te
      split: train
  query:
    init_args:
      _target_: modules.processors.mrag_dataset_processor.TydiQA
      langcode: te
      language: telugu
      split: validation
test:
  doc: null
  query: null
train:
  doc: null
  query: null
