dev:
  doc:
    init_args:
      _target_: modules.dataset_processor.KILT100w
      split: full
  query:
    init_args:
      _target_: modules.processors.mrag_dataset_processor.TydiQA
      langcode: en
      language: english
      split: validation
test:
  doc: null
  query: null
train:
  doc: null
  query: null
