dev:
  doc:
    init_args:
      _target_: modules.dataset_processor.Wiki_monolingual_100w
      lang: id
      split: train
  query:
    init_args:
      _target_: modules.processors.mrag_dataset_processor.TydiQA
      langcode: id
      language: indonesian
      split: validation
test:
  doc: null
  query: null
train:
  doc: null
  query: null
