dev:
  doc:
    init_args:
      _target_: modules.dataset_processor.Wiki_monolingual_100w
      lang: fi
      split: train
  query:
    init_args:
      _target_: modules.processors.mrag_dataset_processor.TydiQA
      langcode: fi
      language: finnish
      split: validation
test:
  doc: null
  query: null
train:
  doc: null
  query: null
