init_args: 
  _target_: models.retrievers.dense.Dense
  model_name: "Shitao/RetroMAE_MSMARCO_distill"
  max_len: 256
  pooler:
    _target_: models.retrievers.dense.ClsPooler
  similarity: 
    _target_: models.retrievers.dense.DotProduct
batch_size: 512
batch_size_sim: 2048