train:
    doc: null
    query: null
dev:
    doc:
      init_args:
        _target_: modules.dataset_processor.Wiki_monolingual_100w
        split: train
        lang: ar
    query:
      init_args:
        _target_: modules.dataset_processor.XORQA
        split: dev
        lang: ar
test:
    doc: null
    query: null