train:
    doc: null
    query: null
dev:
    doc:
      init_args:
        _target_: modules.dataset_processor.MergedDocDataset
        in_dataset_names: ["kilt-100w", "wiki-100w-ja"]
        in_dataset_splits: ["full", "train"]
        out_dataset_name: "wiki-100w-en-ja"
        split: "train"
    query:
      init_args:
        _target_: modules.dataset_processor.XORQA
        split: dev
        lang: ja
test:
    doc: null
    query: null