dev:
  doc:
    init_args:
      _target_: modules.processors.mrag_dataset_processor.XPQA
      lang: ar
      split: test
  query:
    init_args:
      _target_: modules.processors.mrag_dataset_processor.XPQA
      lang: ar
      split: test
test:
  doc: null
  query: null
train:
  doc: null
  query: null
