# main_config.yaml

defaults:
    - _self_
    - retriever: null
    - reranker: null
    - generator: null
    - dataset: ??
    - train: null
    - prompt: basic

# main variables locating the local data folder and index
run_name: null
dataset_folder: '/nfs/data/calmar/indexes_for_reranker/datasets/'
index_folder: '/nfs/data/calmar/indexes_for_reranker/indexes/'
runs_folder: '/nfs/data/calmar/indexes_for_reranker/runs/'
generated_query_folder: 'generated_queries/'
processed_context_folder: 'processed_contexts/'
experiments_folder: '/nfs/data/calmar/indexes_for_reranker/experiments/'    

# topk documents to retrieve, rerank and to use for generation
retrieve_top_k: 50
rerank_top_k: 50
generation_top_k: 5


#
pyserini_num_threads: 20
processing_num_proc: 40
hydra:
    job:
        chdir: False
