# main_config.yaml

defaults:
    - _self_
    - retriever: null
    - reranker: null
    - generator: null
    - dataset: ut1
    - prompt: basic

retrieve_top_k: 10
rerank_top_k: 5
generation_top_k: 5
pyserini_num_threads: 4
run_name: null
dataset_folder: null
index_folder: null
runs_folder: null
experiments_folder: null
processing_num_proc: 40
overwrite_run: true
hydra:
    job:
        chdir: False
