dev:

    # retrieve from oracle docs for HumanEval and MBPP

    # doc: 
    #     init_args:
    #         _target_: modules.dataset_processor.CodeRAGBench_programming_solutions
    #         split: "train"

    # retrieve from all other docs

    doc: 
        init_args:
            _target_: modules.dataset_processor.MergedDocDataset
            in_dataset_names: ["CodeRAGBench_online_tutorials", "CodeRAGBench_library_documentation", "CodeRAGBench_stackoverflow", "CodeRAGBench_gitrepospython", "CodeRAGBench_gitrepos"]
            in_dataset_splits: ["train", "train", "train", "train", "train"]
            out_dataset_name: "CodeRAGBench_database_by_source_minus_humaneval"
            split: "train"

    query: 
        init_args:
            _target_: modules.dataset_processor.CodeRAGBench_HumanEval   # modules.dataset_processor.CodeRAGBench_MBPP
            split: "train"
test:
    doc: null
    query: null