train:
    doc: null
    query: 
        init_args:
            _target_: modules.processors.kilt_dataset_processor.KILTTriviaqa
            split: "train"
    doc: 
        init_args:
            _target_: modules.dataset_processor.KILT100w
            split: "full"
    
    query: 
        init_args:
            _target_: modules.processors.kilt_dataset_processor.KILTTriviaqa
            split: "validation"
test:
    doc: null
    query: null